model:
  model_class: 'UNetSeResNet'
  model_args:
    in_channels: 40
    stem_channels: 64
    down_channels: [64, 128, 256]
    down_kernel_sizes: [3, 5, 7]
    down_strides: [1, 1, 1]
    res_kernel_sizes: [3, 5, 7]
    res_se_ratios: [2, 2, 2]
    res_block_depth: 3
  model_checkpoint_path: null

training:
  folds: [5]
  metric_frequency: 0
  loss_function: 'MSELoss'
  loss_function_args: {}
  training_batch_size: 4096
  test_batch_size: 8192
  num_workers: 16
  random_state: 42
  deterministic_cudnn: False
  device: 'cuda'
  optimizer: 'AdamW'
  optimizer_args:
    lr: 0.001
    betas: [0.9, 0.999]
    weight_decay: 0.01
  lr_scheduler: 'OneCycleLR'
  lr_scheduler_args:
    max_lr: 0.001
    total_steps: 39420
    pct_start: 0.1
    anneal_strategy: 'cos'
    div_factor: 10
    final_div_factor: 1
    last_epoch: -1
  amp: False
  epochs: 50
  early_stopping_metric: 'loss'
  early_stopping_patience: 0

test:
  folds: [1, 2, 3, 4, 5]
  model_file_names: [
    'model_fold_1_epoch_24_best_loss_0.259380.pt',
    'model_fold_2_epoch_12_best_loss_0.271720.pt',
    'model_fold_3_epoch_19_best_loss_0.251861.pt',
    'model_fold_4_epoch_20_best_loss_0.255766.pt',
    'model_fold_5_epoch_19_best_loss_0.249992.pt'
  ]

submission:
  model_file_names: [
    'model_fold_1_epoch_24_best_loss_0.259380.pt',
    'model_fold_2_epoch_12_best_loss_0.271720.pt',
    'model_fold_3_epoch_19_best_loss_0.251861.pt',
    'model_fold_4_epoch_20_best_loss_0.255766.pt',
    'model_fold_5_epoch_19_best_loss_0.249992.pt'
  ]

persistence:
  save_prediction_visualizations: True
  save_best_metrics: ['loss']
  save_epochs: []
